platform:
  - x64

image:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 6

clone_folder: c:\projects\face-recognition

install:
  - cmd: choco install cmake -y
  - cmd: choco upgrade cmake
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - SET PATH=%PATH%;C:\Program Files\CMake\bin;

build: off

test_script:
  - cd c:\projects\face-recognition
  - npm install
  - npm test